//
//  STHTTPRequest+Error.h
//  OBPKit
//
//  Created by Torsten Louland on 16/06/2016.
//  Copyright (c) 2016-2017 TESOBE Ltd. All rights reserved.
//

#import <STHTTPRequest/STHTTPRequest.h>



@interface STHTTPRequest (Error)
- (NSError*)errorByAddingServerSideDescriptionToError:(NSError*)inError; ///< Given an error just generated by an STHTTPRequest instance, check if the request already received a server-side description of the error, and if so create a new error with the server-side error description added.
@end
